apiVersion: v1
kind: ConfigMap
metadata:
  # 配置文件名称
  name: alertmanager-config
  namespace: monitor
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      # 告警自定义邮件
      smtp_smarthost: "smtp.sina.com:25"
      smtp_from: "zengwj1949@sina.com"
      smtp_auth_username: "zengwj1949@sina.com"
      smtp_auth_password: "abc-123."
      smtp_require_tls: false

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      receiver: 'email'
      repeat_interval: 5m

    receivers:
    - name: 'email'
      email_configs:
      - to: "2962372861@qq.com"
        headers: { Subject: " WARNING-告警邮件" }
        send_resolved: true
      - to: "zengwj1949@sina.com"
        headers: { Subject: " WARNING-告警邮件" }
        send_resolved: true

