apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-webhook-dingtalk
  namespace: monitor
  labels:
    app: prometheus-webhook-dingtalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-webhook-dingtalk
  template:
    metadata:
      labels:
        app: prometheus-webhook-dingtalk
    spec:
      containers:
      - args:
        - --ding.profile=webhook1=https://oapi.dingtalk.com/robot/send?access_token=c0f2313bc37c034a999c5801fdbf2de97b3e6e6097499b2f3c1ac8d6791a4583
        name: prometheus-webhook-dingtalk
        image: quay.io/timonwong/prometheus-webhook-dingtalk
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitor
  name: prometheus-webhook-dingtalk
  labels:
    app: prometheus-webhook-dingtalk
spec:
  selector:
    app: prometheus-webhook-dingtalk
  ports:
  - name: dingtalk-port
    port: 8060
    targetPort: 8060
    protocol: TCP
